# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
    tags:
      - v1.*

jobs:
  release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Create archive
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd bin/Release/net8.0
        7z a il2cpp_dump_formatter.zip il2cpp_dump_formatter.dll il2cpp_dump_formatter.exe il2cpp_dump_formatter.runtimeconfig.json
    - name: Create release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: bin/Release/net8.0/il2cpp_dump_formatter.zip
